print("Hello World")
print("hello")
print(3*8)
print(50/10)
print(50//10)
print(50%10)
print('Hello World')
print('Hello World!')
print("This is a \nmutli line string\n")
print("pass" + "word")
print("Ha" * 4)
print("double".find('s'))
print("double".find('u'))
print("double".find('o)'))
print("double".find('b'))
print("double".find('e'))
print("double".find('d'))
print("TestInG.lower()")
print("testiNG.upper()")
print("TestING".lower())
print("tESTing".upper())
print("double".find('d'))
1 + 1
